### ISSUE TITLE
Allow forwarding to another `FromRequest` implementation

### ISSUE THREAD

**Issue by jonas-schievink** [1aim/hyperdrive#10]
For large apps, specifying all possible routes in a single enum doesn't really scale. It would be handy if there was some attribute for specifying that another `FromRequest` impl should be used if none of the routes in the current type match.

Strawman example (please post ideas for a better syntax):

```
#[derive(FromRequest)]
enum Routes {
    #[get("/static/{path...}")]
    Static { path: String },

    #[fallback]  // "if no route attribute matches, use this instead"
    Other {
        #[forward]  // "call FromRequest of this type"
        other: OtherRoutes,
    },
}
```

This would introduce 2 independent features, `#[fallback]` and `#[forward]` (is `#[passthrough]` a better name?).

We'll have to figure out how a forwarded FromRequest call interacts with `Guard`s and `FromBody`. `#[body]` can probably not be combined with this, but `Guard`s and `#[query_params]` should work fine.

**Comment by meh** [comment]
What if we only offer namespacing instead? `fallback` and `forward` seem complicated.

```rust
#[derive(FromRequest)]
enum Routes {
  #[namespace("/user")]
  User(UserRoutes),

  #[namespace("/dog")]
  Dog(DogRoutes),
}

#[derive(FromRequest)]
struct User {
    #[get("/:id")]
    Get { id: String },
}
```

**Comment by jonas-schievink** [comment]
Yeah that sounds like a good idea to consider

**Comment by jonas-schievink** [comment]
Another thing to consider: `#[derive(FromRequest)]` should eventually support structs and not just enums, and then this feature could be used to put a request guard on *all* routes (currently guard are only per-route, and specifying the same guard for *every single route* is very cumbersome).

```rust
#[derive(FromRequest)]
struct MainRoutes {
    logged_in: LogInGuard,
    #[forward]
    route: Route,
}
```

Here, `Route` would be a normal `enum` deriving `FromRequest` and routing requests to endpoints. It does not have to care about the log in guard at all, since it's already handled.

**Comment by meh** [comment]
How would it work on structs? Aside from the guard chaining thing.

**Comment by meh** [comment]
As in, maybe it could work as container attributes instead of field?

```rust
#[derive(FromRequest)]
#[guard(...)]
enum Request { }
```

Is it possible to use any kind of `tt` in that part of a custom attribute?

**Comment by jonas-schievink** [comment]
Yes, `#[guard]` would also be an option.

For the custom derive, I would essentially treat the struct the same as an enum with just a single variant, so technically we could even allow route attributes on there.

**Comment by jonas-schievink** [comment]
One usecase that I think is very valuable is having a global `logged_in_user: User` guard, which is available for every route without having to redeclare it every time. I think using an extra struct and `#[forward]` would allow this in the most natural way, while `#[guard]` doesn't really.

**Comment by meh** [comment]
And if it supported generics you could define guard groups.

```rust
#[derive(FromRequest)]
struct Authenticated<R> {
  logged_in: LogInGuard,

  #[forward]
  request: R,
}

Authenticated<MyRoutes>
Authenticated<SomeOtherRoutes>
```

**Comment by jonas-schievink** [comment]
Oooh now *that* is cool! Okay, I think something like `#[forward]`/`#[passthrough]` is the way to go then.

**Comment by meh** [comment]
I'd rather have `forward` and `namespace`, and forget `passthrough` :panda_face: 

They're for two different uses, and they can work together as well.

**Comment by jonas-schievink** [comment]
Support for structs and generics is now in place. That leaves only `#[forward]` to be implemented. `#[namespace]` can come later (or can be done in a manual `FromRequest` impl).
